apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Values.secret.name }}
  annotations:
    replicator.v1.mittwald.de/replicate-to: {{ .Values.secret.namespace }}
data:
  username: {{ .Values.secret.username | default (randAlphaNum 10) | b64enc | quote }}
  password: {{ .Values.secret.password | default (randAlphaNum 64) | b64enc | quote }}
  connectionString: {{ .Values.secret.connectionString | b64enc | quote }}

